Update package.json
JSHint is required for gulp-jshint to function otherwise it will throw error like the following

Error: Cannot find module 'jshint/src/cli'

Install jshint using the following command:

> npm install --save-dev jshint